#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.

# source: https://linuxize.com/post/ps-command-in-linux/
ps -auxf
