#!/usr/bin/env bash
# This script displays the string "Best School" 10 times.
# Using while loop.
# A counter is generated to note the number of iterations.

count=0

while[$count -lt 10]
do
	echo "Best School"
	count = $((count+1))
done
